return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    config = function()
      require("nvim-treesitter.configs").setup({
        highlight = { enable = true },
        indent = { enable = true },
        sync_install = false,
        auto_install = true,
        ensure_installed = {
          "bash",
          "css",
          "csv",
          "diff",
          "gitignore",
          "html",
          "http",
          "ini",
          "jinja",
          "json",
          "jsonc",
          "lua",
          "luadoc",
          "luap",
          "markdown",
          "markdown_inline",
          "nginx",
          "python",
          "query",
          "regex",
          "sql",
          "tmux",
          "toml",
          "vim",
          "vimdoc",
          "xml",
          "yaml",
        },
      })
    end,
  },
}
